# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ('-read_at',)},
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
